# Generated by Django 3.0.3 on 2020-05-13 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('phoneNumber', models.IntegerField()),
                ('activated', models.BooleanField(default=False)),
                ('employedAt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinics.Clinic')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docAccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('policyNumber', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('phoneNumber', models.IntegerField()),
                ('activation_link', models.CharField(default='', max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicAdmin',
            fields=[
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('phoneNumber', models.IntegerField()),
                ('activated', models.BooleanField(default=False)),
                ('employedAt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='clinics.Clinic')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminAccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Firday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='users.Doctor')),
            ],
            options={
                'unique_together': {('day', 'employee')},
            },
        ),
    ]
