# Generated by Django 3.0.3 on 2020-05-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_personalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='personalID',
            field=models.IntegerField(unique=True),
        ),
    ]
