# Generated by Django 3.0.3 on 2020-05-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200515_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='personalID',
        ),
    ]
