# Generated by Django 3.0.3 on 2020-05-28 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0018_holiday_resolved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_remove_patient_personalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicadmin',
            name='changedPass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='changedPass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clinicadmin',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('phoneNumber', models.IntegerField()),
                ('activated', models.BooleanField(default=True)),
                ('changedPass', models.BooleanField(default=False)),
                ('employedAt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to='clinics.Clinic')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurseAccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
