# Generated by Django 3.0.3 on 2020-05-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200530_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicadmin',
            name='activated',
        ),
        migrations.AlterField(
            model_name='clinicadmin',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
