# Generated by Django 3.0.3 on 2020-05-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200530_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicadmin',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='approved',
        ),
    ]
