# Generated by Django 3.0.3 on 2020-05-13 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='users.Doctor'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='typeOf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.AppointmentType'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='appointmentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='clinics.AppointmentType'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='clinics.Clinic'),
        ),
        migrations.AddField(
            model_name='operatingroom',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_rooms', to='clinics.Clinic'),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_card', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='doctorrating',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.Doctor'),
        ),
        migrations.AddField(
            model_name='doctorrating',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient'),
        ),
        migrations.AddField(
            model_name='clinicrating',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='clinics.Clinic'),
        ),
        migrations.AddField(
            model_name='clinicrating',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.Clinic'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='operatingRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.OperatingRoom'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='typeOf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.AppointmentType'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('clinic', 'appointmentType'), name='unique appointment type price for clinic'),
        ),
        migrations.AlterUniqueTogether(
            name='operatingroom',
            unique_together={('clinic', 'name')},
        ),
        migrations.AddConstraint(
            model_name='doctorrating',
            constraint=models.UniqueConstraint(fields=('doctor', 'patient'), name='one doctor rating per patient'),
        ),
        migrations.AddConstraint(
            model_name='clinicrating',
            constraint=models.UniqueConstraint(fields=('clinic', 'patient'), name='one clinic rating per patient'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('clinic', 'date', 'time', 'doctor'), name='unique doctor date time for a clinic'),
        ),
    ]
