# Generated by Django 3.0.3 on 2020-05-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_auto_20200515_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='appointmentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prices', to='clinics.AppointmentType'),
        ),
    ]
