# Generated by Django 3.0.3 on 2020-05-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_auto_20200516_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttype',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='clinics.Clinic'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='appointmentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='clinics.AppointmentType'),
        ),
    ]
