# Generated by Django 3.0.3 on 2020-05-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_auto_20200516_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='appointmentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='clinics.AppointmentType'),
        ),
        migrations.AddConstraint(
            model_name='appointmenttype',
            constraint=models.UniqueConstraint(fields=('clinic', 'typeName'), name='type names in one clinic must be distinct'),
        ),
    ]
