# Generated by Django 3.0.3 on 2020-05-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_auto_20200516_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttype',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='clinics.Clinic'),
        ),
    ]
