# Generated by Django 3.0.3 on 2020-05-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_auto_20200516_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttype',
            name='typeName',
            field=models.CharField(max_length=30),
        ),
    ]
