# Generated by Django 3.0.5 on 2020-05-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_auto_20200516_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='appointmentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='clinics.AppointmentType'),
        ),
    ]
