# Generated by Django 3.0.3 on 2020-05-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_patient_personalid'),
        ('clinics', '0013_auto_20200519_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday', to='users.Doctor')),
            ],
            options={
                'unique_together': {('doctor', 'startDate')},
            },
        ),
    ]
