# Generated by Django 3.0.3 on 2020-05-27 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0015_holiday_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('employee', 'startDate')},
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='doctor',
        ),
    ]
