# Generated by Django 3.0.3 on 2020-05-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200530_0040'),
        ('clinics', '0018_holiday_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='clinics.Clinic')),
                ('doctor', models.ManyToManyField(related_name='operations', to='users.Doctor')),
                ('operatingRoom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.OperatingRoom')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='users.Patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('clinic', 'date', 'time', 'operatingRoom'), name='unique doctor date time,operation, for a clinic'),
        ),
    ]
