# Generated by Django 3.0.3 on 2020-05-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0019_auto_20200530_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='doctor',
            new_name='doctors',
        ),
    ]
