# Generated by Django 3.0.3 on 2020-05-31 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0021_auto_20200531_0111'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operation',
            name='unique doctor date time,operation, for a clinic',
        ),
        migrations.AlterField(
            model_name='specialization',
            name='typeOf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='clinics.AppointmentType'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('clinic', 'date', 'time', 'operatingRoom'), name='unique doctor date time,operation, for a clinic'),
        ),
    ]
