# Generated by Django 3.0.3 on 2020-05-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0022_auto_20200531_1352'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operation',
            name='unique doctor date time,operation, for a clinic',
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('clinic', 'date', 'time', 'operatingRoom'), name='unique room date time, for a clinic'),
        ),
    ]
