# Generated by Django 3.0.3 on 2020-05-31 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0024_auto_20200531_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='typeOf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='clinics.AppointmentType'),
        ),
    ]
