# Generated by Django 3.0.3 on 2020-05-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0025_auto_20200531_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
