# Generated by Django 3.0.5 on 2020-06-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0027_appointmentreport_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
