# Generated by Django 3.0.5 on 2020-06-09 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200530_0040'),
        ('clinics', '0028_appointment_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('health_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clinics.HealthCard')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.Patient'),
        ),
        migrations.DeleteModel(
            name='AppointmentReport',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
